= Changelog
:toc:

All notable changes to this project will be documented in this file.

The format is based on link:https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to link:https://semver.org/spec/v2.0.0.html[Semantic Versioning].




== Unreleased

This is most likely a maintenance release.


=== Updated

* The description of the plugin metadata keeping up with the link:https://github.com/pop-os/launcher/commit/0c7f3631d3d7f03919a7a378c57a5e8a46e4525c[recent convention].

* The database has been reworked.
This shouldn't affect end users overall.
footnote:[This is only listed for the sake of my own sanity. ;p]


=== Fixed

* The cache format has been changed to give more accurate search results.




== 1.2.0 - 2021-10-01

I don't think this is a good application of "Release early, release often" but there are minor behavior changes for the plugin.
Which means a new version of the plugin.


=== Changed

* The plugin can now only accept one bangs database file at a time.
* `force_download` default value from `true` to `false` due to fixed behavior.


=== Fixed

* `force_download` now forces to download the database and use the local plugin path (e.g., `$HOME/.local/share/pop-launcher/plugins`).
This is considered a fix because I didn't realize `force_download` is essentially useless. ;p




== 1.1.0 - 2021-09-30

Main highlight of this release is the addition of plugin-specific configuration.
It should be located in `$POP_PLUGIN_PATH/bangs/config.json`.
Unlike the bangs database, the configuration is not merged between different plugin paths.


=== Added

* A plugin-specific configuration file.
** `force_download` (boolean) lets you configure to force download of database file when missing.
** `max_limit` (number) indicates the maximum number of search results to be returned.
** `db_url` (string) points to the URL of the default bangs database used together with `force_download`.
** `default_bangs` (array[string]) is a list of bangs to be used when no bangs are found from the search query; handy for quicker search especially when you're used to searching with your default search engine of choice.


=== Fixed

* Return the search results sorted by relevance when in the launcher service.
footnote:[Turns out the launcher service sorts the results by default unless `no_sort` is set to `true`.]




== 1.0.0 - 2021-09-26

The initial release.

=== Added

* Limits with a maximum number of search results, bringing the performance up.

* Automatic download of the bangs database from Duckduckgo if the plugin found no database files.
Though, it needs `curl` as a runtime dependency.
