= Changelog
:toc:

All notable changes to this project will be documented in this file.

The format is based on link:https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to link:https://semver.org/spec/v2.0.0.html[Semantic Versioning].


== Unreleased

Release date is whenever I maintained or remembered this project exists. ;p

=== Added

* A plugin-specific configuration file.
** `force_download` (boolean) lets you configure to force download of database file when missing.
** `max_limit` (number) indicates the maximum number of search results to be returned.
** `db_url` (string) points to the URL of the default bangs database used together with `force_download`.
** `default_bangs` (array[string]) is a list of bangs to be used when no bangs are found from the search query; handy for quicker search especially when you're used to searching with your default search engine of choice.


=== Fixed

* Return the search results sorted by relevance when in the launcher service.
footnote:[Turns out the launcher service sorts the results by default unless `no_sort` is set to `true`.]




== v1.0.0 - 2021-09-26

The initial release.

=== Added

* Limits with a maximum number of search results, bringing the performance up.

* Automatic download of the bangs database from Duckduckgo if the plugin found no database files.
Though, it needs `curl` as a runtime dependency.
