= Pop launcher bangs plugin
:toc:

:prefix_query: !
:bangs_search_query_prefix: !

A link:https://github.com/pop-os/launcher[Pop launcher plugin] that provides a quick searching interface with link:https://duckduckgo.com/bang[Duckduckgo bangs].

[CAUTION]
====
Beware, spaghetti code is ahead.
I just wanted a reason to use Rust and explore a little bit about the renewed Pop launcher.
Though, I'll maintain this project for a bit (before becoming inactive again ;p).
====




== Prerequisites

You need the following dependencies installed.

* link:https://www.rust-lang.org/[Rust compiler] with the complete toolchain (e.g., Cargo, rustfmt, rust-analyzer)
* GNU Make
* If you have link:http://nixos.org/[Nix package manager] installed, you can simply invoke `nix-shell` and you're done setting up the development environment!

All of the following steps to install are automated with `make install`.
Just be sure to read it to make sure.

* Compile the plugin with the package manager (e.g., `cargo build`) and move the binary to one of the launcher plugin paths (e.g., `$HOME/.local/share/pop-launcher/plugins/${PLUGIN}`).

* Move `src/plugin.ron` since Pop launcher needs it to recognize it as one of the plugins in the same plugin directory as the binary.

* You also need to download the bangs database, preferably from Duckduckgo and put it under the `bangs` plugin folder with the filename `db.json`.




== How to use?

With the plugin in place, prefix the search query with `{prefix_query}` to activate the plugin.
The plugin has a certain format to follow to do its thing.

[source]
----
! ${BANG} ${SEARCH_QUERY}...
----

* The first argument is the bang query which is a comma-delimited list of bangs to be searched.
The plugin will give search results based from the last bang from the query.

* The search query is the rest of the argument, it doesn't affect the search of the database.
+
You can also search bangs within the search query by prepending it with `{bangs_search_query_prefix}`.
It is only valid if it's the last part of the search query.

Here's some examples of the plugin in use.

[source]
----
# Search in Arch Wiki
! aw hello there

# Search in Arch Wiki and Duckduckgo
! aw,ddg hello world
----

This plugin should have the following list of features:

* Upon activation, the plugin will open each of the URL and close.
* The plugin has a tab completion which will replace the latest bang with the selected bang into the bang query.





== Issues

* Performance is not great.
It is especially notable as you type quickly.

* Inconsistent search results (e.g., `{prefix_query} aw hello` versus `{prefix_query} aw hello there`).
It should stay the same.




== Frequently asked questions

[qanda]
What is the difference from the built-in web plugin?::
Among other things, this plugin can search multiple pages with one query and takes advantages of Duckduckgo's massive list of them which you can customize it if you want to.
If you think about it, not much.
Both plugins are just getting a list of web search engines from a database, attaching your input to their respective URLs, and opening them with `xdg-open`.
In fact, much of this plugin's source code is based from the web plugin (in other words, it's more like a fork than something else).

Is there a configuration file?::
The configuration file is just Duckduckgo's bangs database placed in `$POP_PLUGIN_PATH/bangs/db.json`.
You can customize it if you want to, add or remove some bangs if you're impatient for the submission process (like me).




== TODO

* [ ] Improve performance, pls.
Maybe, cache the results.
footnote:[I need to learn how to profile programs *properly*.]

* [ ] Automatic downloading of the bangs database in the home folder when running for the first time (or if there's no bangs database anywhere).




== Acknowledgements

* Much of the code are copied (READ: stolen) from the https://github.com/pop-os/launcher/tree/master/plugins/src/web[web built-in launcher plugin].
* The link:https://github.com/dhelmr/ulauncher-duckduckgo-bangs[Ulauncher Duckduckgo bangs extension] as one of the inspirations for the interface.
