= Pop launcher bangs plugin
:toc:

:prefix_query: !

A link:https://github.com/pop-os/launcher[Pop launcher plugin] that provides a quick searching interface with link:https://duckduckgo.com/bang[Duckduckgo bangs].

[CAUTION]
====
Beware, spaghetti code is ahead.
I just wanted a reason to use Rust and explore a little bit about the renewed Pop launcher.
Though, I'll maintain this project for a bit (before becoming inactive again ;p).
====




== Prerequisites

You need the following dependencies installed.

* link:https://www.rust-lang.org/[Rust compiler]
* GNU Make
* If you have link:http://nixos.org/[Nix package manager] installed, you can simply invoke `nix-shell` and you're done setting up the development environment!

To produce the output, compile the plugin with the package manager (e.g., `cargo build`) and move the binary and `src/plugin.ron` (since Pop launcher needs it to recognize it as one of the plugins) to one of the launcher plugin paths (e.g., `$HOME/.local/share/pop-launcher/plugins/${PLUGIN}`).




== How to use?

With the plugin in place, prefix the search query with `{prefix_query}` to activate the plugin.
The plugin has a certain format to follow to do its thing.

[source]
----
! ${BANG} ${SEARCH_QUERY}...
----

* The first argument is the bang query to be searched in the bangs database.
* The search query is the rest of the argument, it doesn't affect the search of the database.




== Issues

* Performance is not great.
It is especially notable as you type quickly.

* Inconsistent search results (e.g., `{prefix_query} aw hello` versus `{prefix_query} aw hello there`).
It should stay the same.




== TODO

* [ ] Improve performance, pls.
Maybe, cache the results.
footnote:[I need to learn how to profile programs *properly*.]

* [ ] Automatic downloading of the bangs database in the home folder when running for the first time (or if there's no bangs database anywhere).




== Acknowledgements

* Much of the code are copied (READ: stolen) from the https://github.com/pop-os/launcher/tree/master/plugins/src/web[web built-in launcher plugin].
* The link:https://github.com/dhelmr/ulauncher-duckduckgo-bangs[Ulauncher Duckduckgo bangs extension] as one of the inspirations for the interface.
