= Pop shell launcher bangs plugin

:toc:

A link:https://github.com/pop-os/launcher[Pop launcher plugin] that provides a quick searching interface with link:https://duckduckgo.com/bang[Duckduckgo bangs].




== Prerequisites

You need the following dependencies installed.

* link:https://www.rust-lang.org/[Rust compiler]
* GNU Make
* If you have link:http://nixos.org/[Nix package manager] installed, you can simply invoke `nix-shell` and you're done setting up the development environment!

To produce the output, compile the plugin with the package manager (e.g., `cargo build`) and move the binary and `src/plugin.ron` (since Pop launcher needs it to recognize it as one of the plugins) to one of the launcher plugin paths (e.g., `$HOME/.local/share/pop-launcher/plugins/${PLUGIN}`).




== Issues

* Performance is not great.
It is especially notable as you type quickly.

* Inconsistent search results (e.g., `! aw hello` versus `! aw hello there`).
It should stay the same.




== TODO

* [ ] Improve performance, pls.
Maybe, cache the results.

* [ ] Automatic downloading of the bangs database in the home folder when running for the first time (or if there's no bangs database anywhere).




== Acknowledgements

* Much of the code are copied (READ: stolen) from the https://github.com/pop-os/launcher/tree/master/plugins/src/web[web built-in launcher plugin].
* The link:https://github.com/dhelmr/ulauncher-duckduckgo-bangs[Ulauncher Duckduckgo bangs extension] as one of the inspirations for the interface.
